
import {useEffect,useState} from 'react';import {BookOpen,ChevronRight,Footprints,IdCard,LockKeyhole,Radio,Trees} from 'lucide-react';import {QRCodeSVG} from 'qrcode.react';import Header from './Header';import NumberPad from './NumberPad';import {store} from '../data/store';import type {LapRange,Student} from '../types';
type Step='home'|'class'|'number'|'code'|'privacy'|'pinSetup'|'pinConfirm'|'pin'|'walk'|'success'|'already';
const laps:{v:LapRange;label:string;icon:string;sub:string}[]=[{v:'1_2',label:'1~2바퀴',icon:'🐾',sub:'가볍게 시작!'},{v:'3_5',label:'3~5바퀴',icon:'🌿',sub:'힘차게 걸었어요'},{v:'6_9',label:'6~9바퀴',icon:'⭐',sub:'정말 대단해요'},{v:'10_PLUS',label:'10바퀴 이상',icon:'🏆',sub:'오늘의 걷기왕'}];
export default function Kiosk(){const [step,setStep]=useState<Step>('home'),[grade,setGrade]=useState(0),[klass,setKlass]=useState(0),[num,setNum]=useState(0),[student,setStudent]=useState<Student>(),[pin,setPin]=useState(''),[firstPin,setFirstPin]=useState(''),[lap,setLap]=useState<LapRange>(),[msg,setMsg]=useState(''),[notice,setNotice]=useState(false),[busy,setBusy]=useState(false);
const reset=()=>{setStep('home');setGrade(0);setKlass(0);setNum(0);setStudent(undefined);setPin('');setFirstPin('');setLap(undefined);setMsg('')};
useEffect(()=>{if(step==='home'||step==='success')return;let left=30;const id=setInterval(()=>{if(--left<=0){clearInterval(id);reset()}},1000);return()=>clearInterval(id)},[step,grade,klass,num,pin,lap]);useEffect(()=>{if(step==='success'){const id=setTimeout(reset,3000);return()=>clearTimeout(id)}},[step]);
const chooseStudent=(n:number)=>{setNum(n);const s=store.find(grade,klass,n);if(!s){setMsg('등록된 학생을 찾지 못했어요. 선생님께 문의해 주세요.');return}setStudent(s);if(!s.consent){setMsg('이용 확인이 필요해요. 선생님께 문의해 주세요.');return}if(store.record(s.id)){setStep('already');return}setStep(s.pin?'pin':'code')};
const verifyPin=()=>{if(!student)return;if(student.lockedUntil&&student.lockedUntil>Date.now()){setMsg('여러 번 잘못 입력했어요. 잠시 후 다시 시도해 주세요.');return}if(pin===student.pin){student.failedAttempts=0;setPin('');setStep('walk')}else{student.failedAttempts++;if(student.failedAttempts>=5){student.lockedUntil=Date.now()+300000;student.failedAttempts=0}setPin('');setMsg('인증번호를 다시 확인해 주세요.')}};
const submit=()=>{if(!student||!lap||busy)return;setBusy(true);setTimeout(()=>{try{store.submit(student.id,lap);setStep('success')}catch{setStep('already')}finally{setBusy(false)}},500)};
const verifyCode=()=>{if(pin===student?.registrationCode){setPin('');setStep('privacy')}else{setPin('');setMsg('등록코드를 다시 확인해 주세요.')}};
const saveFirstPin=()=>{if(pin.length===4){setFirstPin(pin);setPin('');setStep('pinConfirm')}};
const confirmPin=()=>{if(pin===firstPin&&student){student.pin=pin;student.codeUsed=true;setPin('');setStep('walk')}else{setPin('');setFirstPin('');setMsg('인증번호가 달라요. 처음부터 다시 입력해 주세요.');setStep('pinSetup')}};
return <main className="kiosk"><Header onNotice={()=>setNotice(true)}/><section className="stage"><div className="panel primary">{step==='home'?<><div className="seal"><IdCard/></div><h2>학생 인증하기</h2><p>학년, 반, 번호와 인증번호로 안전하게 인증해요.</p><div className="welcome"><Trees/><div><b>아침 걷기 준비됐나요?</b><span>10초면 인증이 끝나요!</span></div></div><button className="hero-btn" onClick={()=>setStep('class')}><Footprints/> 걷기 인증 시작 <ChevronRight/></button></>:<Flow/>}</div><aside className="panel side"><div className="seal"><BookOpen/></div><h2>드라코니스 앱</h2><p>앱이 있는 친구는 QR 코드를 스캔해 보세요!</p><div className="qr"><QRCodeSVG value={import.meta.env.VITE_DRACONIS_QR_URL||'https://example.com/draconis'} size={170}/></div><button className="outline"><BookOpen/> 드라코니스 앱 안내 <ChevronRight/></button><div className="radio"><Radio/><div><b>석암 라디오 신청도 여기에서!</b><span>신청곡과 사연을 보내 보세요.</span></div></div></aside></section>{notice&&<div className="modal"><div><button className="close" onClick={()=>setNotice(false)}>×</button><h2>📣 공지사항</h2>{store.announcements.map((x,i)=><p key={i}>{x}</p>)}<button className="hero-btn" onClick={()=>setNotice(false)}>확인했어요</button></div></div>}</main>;
function Flow(){if(step==='class')return <Choice title="나는 몇 학년인가요?" sub="학년을 선택해 주세요." items={[1,2,3,4,5,6]} suffix="학년" onPick={n=>{setGrade(n);setStep('number')}}/>;if(step==='number'&&!klass)return <Choice title={`${grade}학년, 몇 반인가요?`} sub="반을 선택해 주세요." items={[1,2,3,4,5,6]} suffix="반" onPick={setKlass}/>;if(step==='number')return <Choice title={`${grade}학년 ${klass}반, 몇 번인가요?`} sub="번호를 선택해 주세요." items={Array.from({length:30},(_,i)=>i+1)} suffix="번" onPick={chooseStudent}/>;if(step==='code')return <Pin title="처음 사용하는 학생이에요" sub="선생님께 받은 초기 등록코드를 입력해 주세요." action={verifyCode}/>;if(step==='privacy')return <div className="flow"><BookOpen className="big-icon"/><h2>석암키오스크 이용 안내</h2><p className="notice-copy">아침 걷기 기록 저장을 위해 학년, 반, 번호와 걷기 기록을 사용합니다. 구체적인 안내 문구는 학교 관리자가 운영 기준에 맞게 변경할 수 있습니다.</p><button className="hero-btn" onClick={()=>setStep('pinSetup')}>확인했어요</button></div>;if(step==='pinSetup')return <Pin title="나만의 인증번호를 만들어요" sub="기억하기 쉬운 숫자 4자리를 입력해 주세요." action={saveFirstPin}/>;if(step==='pinConfirm')return <Pin title="한 번 더 입력해 주세요" sub="같은 인증번호를 다시 눌러 주세요." action={confirmPin}/>;if(step==='pin')return <Pin title="인증번호를 입력해 주세요" sub={`${grade}학년 ${klass}반 ${num}번`} action={verifyPin}/>;if(step==='walk')return <div className="flow"><Footprints className="big-icon"/><h2>오늘 운동장을 얼마나 걸었나요?</h2><p>걸은 바퀴 수를 선택해 주세요.</p><div className="laps">{laps.map(x=><button className={lap===x.v?'selected':''} onClick={()=>setLap(x.v)} key={x.v}><span>{x.icon}</span><b>{x.label}</b><small>{x.sub}</small></button>)}</div><button disabled={!lap||busy} className="hero-btn" onClick={submit}>{busy?'기록하고 있어요…':'걷기 인증하기'}</button></div>;if(step==='already')return <div className="flow success"><span className="trophy">🌿</span><h2>오늘 걷기 인증은 이미 완료했어요!</h2><p>오늘 기록: <b>{laps.find(x=>x.v===store.record(student!.id)?.lapRange)?.label}</b></p><button className="hero-btn" onClick={reset}>처음으로</button></div>;return <div className="flow success"><span className="trophy">🏆</span><h2>인증 완료!</h2><p>오늘의 걷기 기록이 저장되었습니다.<br/><b>생명의 숲이 더 건강해졌어요!</b></p><small>3초 후 처음 화면으로 돌아가요.</small></div>}
function Choice({title,sub,items,suffix,onPick}:{title:string;sub:string;items:number[];suffix:string;onPick:(n:number)=>void}){return <div className="flow"><h2>{title}</h2><p>{sub}</p><div className="choices">{items.map(n=><button key={n} onClick={()=>onPick(n)}><b>{n}</b>{suffix}</button>)}</div><button className="back" onClick={reset}>처음으로 돌아가기</button></div>}
function Pin({title,sub,action}:{title:string;sub:string;action:()=>void}){return <div className="flow"><LockKeyhole className="big-icon"/><h2>{title}</h2><p>{sub}</p><div className="dots">{[0,1,2,3].map(i=><i className={pin.length>i?'on':''} key={i}/>)}</div><NumberPad value={pin} onChange={v=>{setPin(v);setMsg('')}}/><p className="error">{msg}</p><button disabled={pin.length!==4} className="hero-btn" onClick={action}>확인</button><button className="text-btn" onClick={()=>setMsg('선생님께 인증번호 초기화를 요청해 주세요.')}>인증번호를 잊었어요</button></div>}}